import { IndentationAwareLexer, IndentationAwareTokenBuilder, type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { QpromptGeneratedModule, QpromptGeneratedSharedModule } from './generated/module.js';
import { QpromptValidator, registerValidationChecks } from './qprompt-validator.js';
import { QpromptValueConverter } from './qprompt-value-converter.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type QpromptAddedServices = {
    validation: {
        QpromptValidator: QpromptValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type QpromptServices = LangiumServices & QpromptAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const QpromptModule: Module<QpromptServices, PartialLangiumServices & QpromptAddedServices> = {
    parser: {
        TokenBuilder: () => new IndentationAwareTokenBuilder(),
        Lexer: (services) => new IndentationAwareLexer(services),
        ValueConverter: () => new QpromptValueConverter()
    },
    validation: {
        QpromptValidator: () => new QpromptValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createQpromptServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Qprompt: QpromptServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        QpromptGeneratedSharedModule
    );
    const Qprompt = inject(
        createDefaultModule({ shared }),
        QpromptGeneratedModule,
        QpromptModule
    );
    shared.ServiceRegistry.register(Qprompt);
    registerValidationChecks(Qprompt);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, Qprompt };
}
